// /**
// * @file This script is auto-generated by create-nitro-module and should not be edited.
// *
// * @description This script applies a workaround for Android by modifying the '<ModuleName>OnLoad.cpp' file.
// * It reads the file content and removes the 'margelo/nitro/' string from it. This enables support for custom package names.
// *
// * @module create-nitro-module
// */
// const path = require('node:path')
// // CHANGE THIS:
// const fs = require('node:fs/promises') // Import the full 'fs' object here
// const { writeFile, readFile } = require('node:fs/promises')
// const { readdir } = require('node:fs/promises')


// const updateViewManagerFiles = async (file) => {
//   const viewManagerFile = path.join(
//     process.cwd(),
//     'nitrogen/generated/android/kotlin/com/margelo/nitro/nitrolist/views',
//     file
//   )

//   const viewManagerStr = await readFile(viewManagerFile, { encoding: 'utf8' })
//   await writeFile(
//     viewManagerFile,
//     viewManagerStr.replace(
//       /com\.margelo\.nitro\.nitrolist\.\*/g,
//       'com.nitrolist.*'
//     )
//   )
// }  


// // const androidWorkaround = async () => {
// //  const androidOnLoadFile = path.join(
// //    process.cwd(),
// //    'nitrogen/generated/android',
// //    'NitroListOnLoad.cpp'
// //  )
 
// //  const viewManagerDir = await readdir(
// //   path.join(
// //     process.cwd(),
// //     'nitrogen/generated/android/kotlin/com/margelo/nitro/nitrolist/views'
// //   )
// //  )
// //  const viewManagerFiles = viewManagerDir.filter((file) =>
// //    file.endsWith('Manager.kt')
// //  )
// //  const res = await Promise.allSettled(
// //    viewManagerFiles.map(updateViewManagerFiles)
// //  )

// //  if (res.some((r) => r.status === 'rejected')) {
// //    throw new Error(`Error updating view manager files: ${res}`)
// //  }

 
// //  const str = await readFile(androidOnLoadFile, { encoding: 'utf8' })
// //  await writeFile(androidOnLoadFile, str.replace(/margelo\/nitro\//g, ''))
// // }
// // androidWorkaround()

// async function androidWorkaround() {
//   const androidRoot = path.join(
//     process.cwd(),
//     'nitrogen/generated/android'
//   );

//   // 1️⃣ If Android was not generated → exit cleanly
//   try {
//     await fs.access(androidRoot);
//   } catch {
//     return;
//   }

//   // 2️⃣ Patch view managers if present
//   const viewManagerDir = path.join(
//     androidRoot,
//     'kotlin/com/margelo/nitro/nitrolist/views'
//   );

//   try {
//     const files = await fs.readdir(viewManagerDir);
//     await Promise.all(
//       files
//         .filter((f) => f.endsWith('Manager.kt'))
//         .map(async (file) => {
//           const filePath = path.join(viewManagerDir, file);
//           const content = await fs.readFile(filePath, 'utf8');
//           await fs.writeFile(
//             filePath,
//             content.replace(
//               /com\.margelo\.nitro\.nitrolist\.\*/g,
//               'com.nitrolist.*'
//             )
//           );
//         })
//     );
//   } catch {
//     // View managers not present → safe no-op
//   }

//   // 3️⃣ Patch OnLoad.cpp if present
//   const onLoadFile = path.join(androidRoot, 'NitroListOnLoad.cpp');

//   try {
//     const content = await fs.readFile(onLoadFile, 'utf8');
//     await fs.writeFile(
//       onLoadFile,
//       content.replace(/margelo\/nitro\//g, '')
//     );
//   } catch {
//     // File not present → safe no-op
//   }
// }

// androidWorkaround();


const path = require('node:path');
const fs = require('node:fs/promises'); // ✅ This is correct in modern Node [cite: 2025-12-29]

// Helper function to update View Managers
const updateViewManagerFiles = async (viewManagerDir, file) => {
  const filePath = path.join(viewManagerDir, file);
  try {
    const content = await fs.readFile(filePath, 'utf8');
    await fs.writeFile(
      filePath,
      content.replace(/com\.margelo\.nitro\.nitrolist\.\*/g, 'com.nitrolist.*')
    );
  } catch (err) {
    console.error(`Failed to patch ${file}:`, err);
  }
};

async function androidWorkaround() {
  const androidRoot = path.join(process.cwd(), 'nitrogen/generated/android');

  // 1️⃣ Check if Android was generated
  try {
    await fs.access(androidRoot);
  } catch {
    return; // Android not generated, skip [cite: 2025-12-29]
  }

  // 2️⃣ Patch View Managers
  const viewManagerDir = path.join(androidRoot, 'kotlin/com/margelo/nitro/nitrolist/views');
  try {
    const files = await fs.readdir(viewManagerDir);
    const managerFiles = files.filter((f) => f.endsWith('Manager.kt'));
    await Promise.all(managerFiles.map(file => updateViewManagerFiles(viewManagerDir, file)));
  } catch {
    // Path doesn't exist, ignore
  }

  // 3️⃣ Patch OnLoad.cpp (The "Handshake" fix for Android)
  const onLoadFile = path.join(androidRoot, 'NitroListOnLoad.cpp');
  try {
    const content = await fs.readFile(onLoadFile, 'utf8');
    // ✅ Removes the hardcoded margelo path to support your custom package [cite: 2024-12-24]
    await fs.writeFile(onLoadFile, content.replace(/margelo\/nitro\//g, ''));
  } catch {
    // File not present, ignore
  }
}

androidWorkaround().catch(err => console.error("Workaround failed:", err));